### ISSUE TITLE
/subscribe endpoint is responding with 500

### ISSUE THREAD

**Issue by m3co-code** [thomasleveil/docker-server-sent-events#1]
I was looking for a SSE server that I can use for integration tests with docker-compose. Your small library looks like a good match, all that I need is provided here.

I was trying it out but it seems the /subscribe endpoint is not working properly. Here is some logoutput and how I started the container:

```sh
➜  traefik git:(fix-SSE-with-retries-enabled) ✗ docker run -d -p 80:80 tomdesinto/server-sent-events

ab5a99f65221b349be74d5e9c138992449f5d4a04a2e8347835d1844093f324a
➜  traefik git:(fix-SSE-with-retries-enabled) ✗ docker ps   
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                NAMES
ab5a99f65221        tomdesinto/server-sent-events   "gunicorn --bind 0..."   30 seconds ago      Up 28 seconds       0.0.0.0:80->80/tcp   practical_hamilton
➜  traefik git:(fix-SSE-with-retries-enabled) ✗ docker logs practical_hamilton
[2017-09-19 15:00:26 +0000] [1] [INFO] Starting gunicorn 19.3.0
[2017-09-19 15:00:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2017-09-19 15:00:26 +0000] [1] [INFO] Using worker: sync
[2017-09-19 15:00:26 +0000] [11] [INFO] Booting worker with pid: 11
[2017-09-19 15:00:41 +0000] [11] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    for item in respiter:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 693, in __next__
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/usr/src/app/server.py", line 88, in gen
    result = q.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
[2017-09-19 15:00:45 +0000] [11] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    for item in respiter:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 693, in __next__
    return self._next()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/usr/src/app/server.py", line 88, in gen
    result = q.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 200, in get
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
```

Do you know what is wrong here? 🐼

**Comment by thomasleveil** [comment]
Hi, I built this years ago to do some integration tests. I have no use for this project now and as such do not intend to maintain it. I hope you understand I cannot provide support on this issue.

If you figure it out, I will gladly accept any PR to fix this.

**Comment by m3co-code** [comment]
Absolute, I understand. I expected that after having a look at the contributions history. Thanks for the quick reply :-)

**Comment by m3co-code** [comment]
I am closing the issue, I won't do a PR for this. Usually I am working in a different tech-stacks.
